### ISSUE TITLE
StorageClass example uses NFs v4.0 whereas it should be v4.1

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/astra-data-store#27]
Page: [Set up Astra Data Store preview components](https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html)

In section "Create a default Astra Data Store storage class"

The shown StorageClass defines NFS mount option vers=4. Astra Data Store does only support version 4.1, so it should read "vers=4.1".

Current version in the docs:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=4
```

Corrected version:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - vers=4.1
 ```
